name: Makefile CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@master

    - name: Install dependencies
      run: sudo apt get install make

    - name: make
      run: cd 按键点灯 && make

